const DOG_BREEDS = [
  'afador','affenhuahua','affenpinscher', 'afghan hound', 'airedale terrier',
  'akbash', 'akita', 'akita chow', 'akita pit', 'akita shepherd', 'alaskan malamute',
  'alaskan klee kai', 'alaskan husky', 'american bulldog', 'american english coonhound',
  'american eskimo dog', 'american foxhound', 'american hairless terrier',
  'american pit bull terrier', 'american pugabull', 'american staffordshire terrier',
  'american staffordshire', 'american water spaniel', 'anatolian shepherd dog',
  'appenzeller sennenhunde', 'auggie', 'aussiedoodle', 'Aussiepom',
  'australian cattle dog', 'australian kelpie', 'australian retriever', 'australian shepherd',
  'australian shepherd husky', 'australian shepherd lab mix', 'australian shepherd pit bull mix',
  'australian stumpy tail cattle dog', 'australian terrier', 'azawakh',
  'babvet', 'basenji', 'bassador', 'basset fauve de bretagne','basset hound',
  'basset retriever', 'bavarian mountain scent hound', 'beabull', 'beagle',
  'beaglier', 'bearded collie', 'bedlington terrier', 'belgian laekenois', 'belgian malinois',
  'belgian sheepdog', 'belgian tervuren', 'Bergamasco Sheepdog', 'Berger Picard',
  'Bernedoodle', 'Bernese Mountain Dog', 'Bichon Frise', 'Biewer Terrier', 'Black and Tan Coonhound',
  'Black Mouth Cur', 'Black Russian Terrier', 'Bloodhound', 'Blue Lacy',
];
